@php
    /*
    |--------------------------------------------------------------------------
    | Stylesheet and script
    |--------------------------------------------------------------------------
    | Three ways this can be served, in order of preference:
    |
    |   1. `npm run dev` is running          → Vite's hot server
    |   2. a Vite build exists AND is fresh  → public/build
    |   3. otherwise                         → the pre-compiled public/css/theme.css
    |
    | Step 2 checks the build's age on purpose. `public/build/` is generated by
    | npm and is not in the project zip, so unzipping a new version updates
    | `public/css/theme.css` and leaves an old build sitting there — and Laravel
    | would keep serving the stale one. The page then shows yesterday's CSS with
    | today's HTML, which looks like the fix did not work rather than like a
    | caching problem, and costs an afternoon to find.
    |
    | So: if the build is older than the compiled fallback, the build is out of
    | date and the fallback wins. Run `npm run build` to make it authoritative
    | again, or delete `public/build/` if you are not using Vite at all.
    */
    $hot = file_exists(public_path('hot'));
    $manifest = public_path('build/manifest.json');
    $fallback = public_path('css/theme.css');

    $useVite = $hot || (
        file_exists($manifest)
        && (! file_exists($fallback) || filemtime($manifest) >= filemtime($fallback))
    );
@endphp

@if ($useVite)
    @vite(['resources/css/app.css', 'resources/js/app.js'])
@else
    {{-- filemtime busts the browser cache whenever build-fallback.php reruns --}}
    <link rel="stylesheet" href="{{ asset('css/theme.css') }}?v={{ filemtime($fallback) }}" />
    <script src="{{ asset('js/theme.js') }}?v={{ filemtime(public_path('js/theme.js')) }}" defer></script>

    @if (file_exists($manifest))
        {{-- Say it out loud rather than failing quietly. --}}
        <!-- Nova: public/build is older than public/css/theme.css, so the
             pre-compiled stylesheet is being used. Run `npm run build` or
             delete public/build/ to stop seeing this. -->
    @endif
@endif
