<?php

/*
|--------------------------------------------------------------------------
| Offline fallback builder
|--------------------------------------------------------------------------
| Copies resources/css/app.css and resources/js/app.js into public/ with the
| Tailwind-only directives stripped, so the theme still renders correctly
| before anyone has run `npm install && npm run build`.
|
|   php scripts/build-fallback.php
|
| Delete this script (and public/css/theme.css, public/js/theme.js) if you
| always build assets with Vite.
*/

$root = dirname(__DIR__);

$css = file_get_contents($root . '/resources/css/app.css');
$css = preg_replace('#/\* nova:tailwind-only:start \*/.*?/\* nova:tailwind-only:end \*/#s', '', $css);
$css = "/* Generated by scripts/build-fallback.php — edit resources/css/app.css instead. */\n" . ltrim($css);

@mkdir($root . '/public/css', 0755, true);
@mkdir($root . '/public/js', 0755, true);

file_put_contents($root . '/public/css/theme.css', $css);
file_put_contents(
    $root . '/public/js/theme.js',
    "/* Generated by scripts/build-fallback.php — edit resources/js/app.js instead. */\n"
        . file_get_contents($root . '/resources/js/app.js')
);

// Page-specific scripts are copied across as they are.
foreach (glob($root . '/resources/js/*.js') as $file) {
    if (basename($file) === 'app.js') {
        continue;
    }

    file_put_contents(
        $root . '/public/js/' . basename($file),
        "/* Generated by scripts/build-fallback.php — edit resources/js/" . basename($file) . " instead. */\n"
            . file_get_contents($file)
    );
}

// Page-specific stylesheets too — print.css is not part of the theme, since a
// printed document has no dark mode and no cards.
foreach (glob($root . '/resources/css/*.css') as $file) {
    if (basename($file) === 'app.css') {
        continue;
    }

    file_put_contents(
        $root . '/public/css/' . basename($file),
        "/* Generated by scripts/build-fallback.php — edit resources/css/" . basename($file) . " instead. */\n"
            . file_get_contents($file)
    );
}

echo "Wrote public/css/theme.css and public/js/theme.js\n";
